# סטיקרים לטעינה בעת עיבוד טקסט של מספר רכב
LICENSE_PLATE_STICKERS = [
    "CAACAgEAAxkBAAEOdx1oIl5SiRGr8MdaXGv-fFh1YvsqPgACtgIAAk8C2EawnAhyEryg3TYE",
    "CAACAgEAAxkBAAEOdx9oIl6OIPTprdkAAa3aKPmL0bvrlXcAAjkEAAJHpxlETlv1LldFLEQ2BA",
    "CAACAgIAAxkBAAEOdyFoIl6ancyVJ449DVytfUK0gwABcz4AAksCAAJWnb0KYlBF0FD6cZw2BA",
    "CAACAgIAAxkBAAEOdydoIl9n0aIp9BpkV_HAzt7zzr74AAPvDAAC18bxSnuZNkCo-dJnNgQ",
    "CAACAgIAAxkBAAEOdyloIl96w8VgzoEn7bjDnEFu5JoLkQAC0AkAAowt_Qc89_7kt1u7szYE",
    "CAACAgIAAxkBAAEOdytoIl-JMmXiJa2VXUqNKbkXu33WOQACTVQAAmH0SUq_8VQbtwOFgjYE",
    "CAACAgEAAxkBAAEOdy1oIl-0gFVAwCeR2_MRFnDnlTMBLgACIgMAAma-oUY566OY856vSzYE",
    "CAACAgIAAxkBAAEOdy9oIl_EUypB5oOBXVXZRmjebI3EdQACHxAAAnCswEgvF961dhIdtzYE",
    "CAACAgIAAxkBAAEOdzFoImA0UsGLzDbXuT0oBGiMplAFEwACwQoAAh5hoUpZi8YqzCzJ5TYE",
    "CAACAgIAAxkBAAEOdzNoImA76lh2h34tMPo9_x3KguxxgQACESEAAnLDQEhgZeBxMNdpAjYE",
    "CAACAgEAAxkBAAEOdzVoImCb-EnNOThpo01b8IfM9zHftAACkQMAAm61IUTQ2KZBkzXupDYE",
]

# סטיקרים לטעינה בעת עיבוד תמונה
PHOTO_STICKERS = [
    "CAACAgIAAxkBAAEOdkRoIgvpc4P3QzgI3yaRgbt0nsAQ9wAC-BIAAlo16Uhs4hFMpJkFTjYE",
    "CAACAgIAAxkBAAEOdktoIgyYCo0zN0xajTvyeNongDA4xwACVQADr8ZRGmTn_PAl6RC_NgQ",
    "CAACAgIAAxkBAAEOdlloIgyx5b4QE7fkXXg38g72OixomwACJQ8AAkuTkUjrHBy-H6OZCjYE",
    "CAACAgIAAxkBAAEOdwhoIly1GVZ87f4ytQABoNRh5qWq8KkAAmcLAAJFsfFKYW0imca0hI02BA",
    "CAACAgIAAxkBAAEOdwpoIlzP5lFtcAyQwjdMTJO_JVuhqAACogEAAladvQpBnnI7eRH13TYE",
    "CAACAgIAAxkBAAEOdwxoIlzj1wABipiEOpekBr7MDLvF1-kAAtgAA6tXxAsSurtX4BbuKTYE",
]